### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit/vyakarana#1]
I am deeply impressed by the logical classification in the readme at http://vyakarana.readthedocs.io/en/latest/.
I am interested to know the present status of development and the issues in the coding.
Appreciate any feedback

**Comment by akprasad** [comment]
Someone mentioned this repo on my Discord server, and I realized I never replied to this issue! Forgive me for that.

It's been 6 years since this issue was opened, but I believe you now know from our email swhat the present state of this work is (github.com/ambuda-org/vidyut).
